apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelab-buurtsporen
  labels:
    app: timelab-buurtsporen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelab-buurtsporen
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timelab-buurtsporen
    spec:
      containers:
        - name: timelab-buurtsporen
          image: {{container-image}}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: {{DATABASE_URL}}
            - name: AWS_ACCESS_KEY_ID
              value: {{AWS_ACCESS_KEY_ID}}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{AWS_SECRET_ACCESS_KEY}}
            - name: AWS_REGION
              value: europe-west1
            - name: AWS_ENDPOINT
              value: https://storage.googleapis.com
            - name: S3_BUCKET_NAME
              value: buurtsporen
          volumeMounts:
            - name: storage
              subPath: upload
              mountPath: /app/upload
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: timelab-buurtsporen-storage
