apiVersion: apps/v1
kind: Deployment
metadata:
  name: asasense-api-backend
  labels:
    app: asasense-api-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asasense-api-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asasense-api-backend
    spec:
      containers:
        - name: asasense-api-backend
          image: container-image
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: {{DATABASE_URL}}
