apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelab-buurtsporen
  labels:
    app: timelab-buurtsporen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelab-buurtsporen
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: timelab-buurtsporen
    spec:
      containers:
        - name: timelab-buurtsporen
          image: {{container-image}}
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: {{DATABASE_URL}}
